/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_mihosoft_vfxwebkit_NativeBinding */

#ifndef _Included_eu_mihosoft_vfxwebkit_NativeBinding
#define _Included_eu_mihosoft_vfxwebkit_NativeBinding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_mihosoft_vfxwebkit_NativeBinding
 * Method:    pageBuffer
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_eu_mihosoft_vfxwebkit_NativeBinding_pageBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     eu_mihosoft_vfxwebkit_NativeBinding
 * Method:    pageBufferDirect
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_eu_mihosoft_vfxwebkit_NativeBinding_pageBufferDirect
  (JNIEnv *, jobject, jint);

/*
 * Class:     eu_mihosoft_vfxwebkit_NativeBinding
 * Method:    isDirty
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_mihosoft_vfxwebkit_NativeBinding_isDirty
  (JNIEnv *, jobject, jint);

/*
 * Class:     eu_mihosoft_vfxwebkit_NativeBinding
 * Method:    setDirty
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vfxwebkit_NativeBinding_setDirty
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     eu_mihosoft_vfxwebkit_NativeBinding
 * Method:    load
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vfxwebkit_NativeBinding_load
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eu_mihosoft_vfxwebkit_NativeBinding
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vfxwebkit_NativeBinding_init
  (JNIEnv *, jobject);

/*
 * Class:     eu_mihosoft_vfxwebkit_NativeBinding
 * Method:    lock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vfxwebkit_NativeBinding_lock
  (JNIEnv *, jobject);

/*
 * Class:     eu_mihosoft_vfxwebkit_NativeBinding
 * Method:    unlock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_mihosoft_vfxwebkit_NativeBinding_unlock
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
